im not sure whats happened, i think i have 2 identical repositories a…
jondon94/Portfolio pull request #1
Opened 2017-10-26 07:51 UTC by jondon94

…nd ive been uploading to the wrong one, here is all the latest stuff, all working, further improvements to come

2017-10-26 14:23 UTC, JSChilds commented on profileAbout.html
> +  <body>
The body tag should not be used more than once and shouldn't be nested inside any tag other than html. All the content on a page should be inside the body. For example:

<html>
    <body>
        All the page elements and content goes in here.
    </body> 
</html>

2017-10-26 14:25 UTC, JSChilds commented on prostyle.css
> +.intrests {
Should be spelt "interests" - be careful with spelling, as you may find yourself unable to target things you think you should be able to.

2017-10-26 14:26 UTC, JSChilds requested changes
Change your html to only have one body tag that all the rest of the page content is nested inside.

2017-10-27 10:16 UTC, JSChilds commented on profileAbout.html
> +<!-- <div class="container-fluid">
Try to avoid leaving in commented-out code.

2017-10-27 10:17 UTC, JSChilds commented on profileSkills.html
> +
Try to keep spacing consistent when you use it.

2017-10-27 10:17 UTC, JSChilds commented on profileAbout.html
> +  <body>
There should only be one body tag that all the page content is nested inside.

2017-10-27 10:18 UTC, JSChilds requested changes
The body tag issues still need to be changed, but other than that very nice!

2017-10-28 08:41 UTC, richgurney requested changes
Can you change profileHome.html to index.html. To put this on GitHub you will need to have the correct name for the deployment to work

2017-10-29 15:07 UTC, JSChilds commented on profileAbout.html
> +
Everything from here to the end of body should be indented.

2017-10-29 15:10 UTC, JSChilds commented on profileContact.html
> +  <body>
Body tag shouldn't be here.

2017-10-29 15:10 UTC, JSChilds commented on profileHome.html
> +  <body>
Body tag shouldn't be here.

2017-10-29 15:11 UTC, JSChilds requested changes
Still seeing a couple uses of body tags that shouldn't be there. Remember - there should be only one body tag and all the page content should be nested inside it.

2018-02-15 22:04 UTC, merged